#!/bin/bash
#PBS -S /bin/bash
#PBS -N replSpePopinGs
#PBS -o /work/flassall/logs/mrbayes
#PBS -j oe 
#PBS -l walltime=24:00:00 

echo "This is job $PBS_JOBNAME, job_ID $PBS_JOBID (array_task_ID $PBS_ARRAY_INDEX) on host $HOSTNAME, running $PBS_NUM_PPN processes on these workers:"
cat $PBS_NODEFILE
echo ""

# this is specific of the environmnt on which the script was developped
# on other environments, other methods may be applied to make availble the Python igraph package
module load anaconda2/personal
source activate env_python2
## to emulate this on other systems, it is best to build your own conda environment
## where you make sure you are using python 2 and have igraph installed with:
# conda create -n env_python2 python=2.7 python-igraph



# all environment variables should have been passed on by  qsub -V
# verify for the most important
if [ -z "${tasklist}" ] ; then
  echo "Error: mandatory variable \${tasklist} not provied, exit now"
  exit 1
fi
if [ -z "${dtag}" ] ; then
  echo "Error: mandatory variable \${dtag} not provied, exit now"
  exit 1
fi
if [ ! -d "${colalinexuscodedir}/${collapsecond}" ] ; then
  echo "Error: input folder '${colalinexuscodedir}/${collapsecond}' does not exist, exit now"
  exit 1
fi
if [ ! -d "${coltreechains}/${collapsecond}" ] ; then
  echo "Error: output folder '${coltreechains}/${collapsecond}' does not exist, exit now"
  exit 1
fi
if [ ! -s "${speciestree}.lsd.newick" ] ; then
  echo "Error: input ultrametric species tree file '${speciestree}.lsd.newick' does not exist or is empty, exit now"
  exit 1
fi
if [ ! -s "${speciestree%.*}_populations" ] ; then
  echo "Error: input species population file '${speciestree%.*}_populations' does not exist or is empty, exit now"
  exit 1
fi

if [ ! -z "$ncpus" ] ; then
  ncpus=1
fi


taskchunklist=`awk "NR==$PBS_ARRAY_INDEX" ${tasklist}_${dtag}_taskchunks`
if [ -z "${taskchunklist}" ] ; then
  # to cover the case when not running as an array job
  taskchunklist=${tasklist}
  replrun="${dtag}"
else
  jobrange=$(echo $taskchunklist | awk -F'_' '{print $NF}')
  replrun="${dtag}_${jobrange}"
fi

if [ ! -z "${verbosereplSpePopinGs}" ] ; then
  verbosemode="--verbose=${verbosereplSpePopinGs}"
else
  verbosemode=""
fi

python ${ptgscripts}/replace_species_by_pop_in_gene_trees.py -G ${taskchunklist} -c ${colalinexuscodedir}/${collapsecond} -S ${speciestree}.lsd.newick -o ${coltreechains}/${collapsecond} \
 --populations=${speciestree%.*}_populations --population_tree=${speciestree%.*}_collapsedPopulations.nwk --population_node_distance=${speciestree%.*}_interNodeDistPopulations \
 --dir_full_gene_trees=${mlgenetrees}/rootedTree --method=${replmethod} --threads=${ncpus} --reuse=0 --max.recursion.limit=12000 --logfile=${repllogs}_${replrun}.log ${verbosemode}
